In [1]:
#1. Import the NUMPY package under the name np.
import numpy as np

In [2]:
#2. Print the NUMPY version and the configuration.
np.version.version

'1.18.5'

In [3]:
#3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
# Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

a = np.random.rand(2,3,5)
b = np.random.randn(2,3,5)
c= np.random.random((2,3,5))

In [4]:
#4. Print a.
print(a)

[[[0.69844279 0.69688006 0.58297364 0.04360507 0.24569185]
  [0.64207982 0.45982848 0.54064419 0.90627485 0.02584606]
  [0.6325976  0.27722996 0.40666216 0.92563858 0.36599275]]

 [[0.53305    0.05262579 0.11339115 0.48986541 0.03672562]
  [0.27252252 0.52592337 0.53250007 0.91469857 0.29278659]
  [0.17472088 0.44080236 0.21960309 0.54540777 0.25407242]]]


In [5]:
#5. Create a 5x2x3 3-dimensional array with all values equaling 1.
#Assign the array to variable "b"
b = np.ones((5,2,3), dtype= int)

In [6]:
#6. Print b.
print(b)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


In [7]:
#7. Do a and b have the same size? How do you prove that in Python code?
print(a.size==b.size)
#same "size" but not "shape" a is 2x3x5 and b is 5x2x3
print(a.shape==b.shape)

True
False


In [8]:
#8. Are you able to add a and b? Why or why not?
#They have different shape

In [9]:
#9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".
c = np.transpose(b, (1,2,0))
print(c.shape)

(2, 3, 5)


In [84]:
#10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?
d = a+c


In [11]:
#11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.
print(a)
print('---------------')
print(d)
#It's a one to one sum of each value of each matrix#12. Multiply a and c. Assign the result to e.



[[[0.69844279 0.69688006 0.58297364 0.04360507 0.24569185]
  [0.64207982 0.45982848 0.54064419 0.90627485 0.02584606]
  [0.6325976  0.27722996 0.40666216 0.92563858 0.36599275]]

 [[0.53305    0.05262579 0.11339115 0.48986541 0.03672562]
  [0.27252252 0.52592337 0.53250007 0.91469857 0.29278659]
  [0.17472088 0.44080236 0.21960309 0.54540777 0.25407242]]]
---------------
[[[1.69844279 1.69688006 1.58297364 1.04360507 1.24569185]
  [1.64207982 1.45982848 1.54064419 1.90627485 1.02584606]
  [1.6325976  1.27722996 1.40666216 1.92563858 1.36599275]]

 [[1.53305    1.05262579 1.11339115 1.48986541 1.03672562]
  [1.27252252 1.52592337 1.53250007 1.91469857 1.29278659]
  [1.17472088 1.44080236 1.21960309 1.54540777 1.25407242]]]


In [20]:
#12. Multiply a and c. Assign the result to e.

e = a*c
print(e)
print('------------')
print(a)

[[[0.69844279 0.69688006 0.58297364 0.04360507 0.24569185]
  [0.64207982 0.45982848 0.54064419 0.90627485 0.02584606]
  [0.6325976  0.27722996 0.40666216 0.92563858 0.36599275]]

 [[0.53305    0.05262579 0.11339115 0.48986541 0.03672562]
  [0.27252252 0.52592337 0.53250007 0.91469857 0.29278659]
  [0.17472088 0.44080236 0.21960309 0.54540777 0.25407242]]]
------------
[[[0.69844279 0.69688006 0.58297364 0.04360507 0.24569185]
  [0.64207982 0.45982848 0.54064419 0.90627485 0.02584606]
  [0.6325976  0.27722996 0.40666216 0.92563858 0.36599275]]

 [[0.53305    0.05262579 0.11339115 0.48986541 0.03672562]
  [0.27252252 0.52592337 0.53250007 0.91469857 0.29278659]
  [0.17472088 0.44080236 0.21960309 0.54540777 0.25407242]]]


In [18]:
#13. Does e equal to a? Why or why not?
a == e
#it is the same one to one

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

In [85]:
#14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)

In [80]:
#15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.

f = np.empty((2,3,5))


In [102]:

#16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
#If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
#If a value equals to d_mean, assign 50 to the corresponding value in f.
#Assign 0 to the corresponding value(s) in f for d_min in d.
#Assign 100 to the corresponding value(s) in f for d_max in d.
#In the end, f should have only the following values: 0, 25, 50, 75, and 100.
#Note: you don't have to use Numpy in this question.

f = np.copy(d)
f[f==d_min]= 0
f[(f>d_min) & (f<d_mean)]= 25
f[f==d_mean]=50
f[(f>d_mean)& (f<d_max)]= 75
f[f==d_max]=100
print(f)




[[[ 75.  75.  75.  25.  25.]
  [ 75.  75.  75.  75.   0.]
  [ 75.  25.  25. 100.  25.]]

 [[ 75.  25.  25.  75.  25.]
  [ 25.  75.  75.  75.  25.]
  [ 25.  75.  25.  75.  25.]]]


In [98]:
#"""
#17. Print d and f. Do you have your expected f?

print(d)
print(f)


[[[1.69844279 1.69688006 1.58297364 1.04360507 1.24569185]
  [1.64207982 1.45982848 1.54064419 1.90627485 1.02584606]
  [1.6325976  1.27722996 1.40666216 1.92563858 1.36599275]]

 [[1.53305    1.05262579 1.11339115 1.48986541 1.03672562]
  [1.27252252 1.52592337 1.53250007 1.91469857 1.29278659]
  [1.17472088 1.44080236 1.21960309 1.54540777 1.25407242]]]
[[[ 75.  75.  75.  25.  25.]
  [ 75.  75.  75.  75.   0.]
  [ 75.  25.  25. 100.  25.]]

 [[ 75.  25.  25.  75.  25.]
  [ 25.  75.  75.  75.  25.]
  [ 25.  75.  25.  75.  25.]]]


In [100]:
#18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values
#("A", "B", "C", "D", and "E") to label the array elements?

f[f==0.]='A'
f[f==25.]='B'
f[f==50.]='C'
f[f==75.]='D'
f[f==100.]='E'





ValueError: could not convert string to float: 'A'