In [1]:
#1. Import the NUMPY package under the name np.
import numpy as np

In [2]:
#2. Print the NUMPY version and the configuration.
np.version.version

'1.18.5'

In [3]:
#3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
# Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

a = np.random.rand(2,3,5)
b = np.random.randn(2,3,5)
c= np.random.random((2,3,5))

In [4]:
#4. Print a.
print(a)

[[[0.16316074 0.75047108 0.14130161 0.70955742 0.85998858]
  [0.93324297 0.18912228 0.1962586  0.0515107  0.70624949]
  [0.02135796 0.10704109 0.54889578 0.73649399 0.98778808]]

 [[0.00635736 0.35127666 0.01824112 0.28142591 0.85660664]
  [0.54823925 0.26497566 0.52960075 0.57961704 0.44223704]
  [0.78766805 0.15292788 0.7055626  0.28157866 0.89320345]]]


In [5]:
#5. Create a 5x2x3 3-dimensional array with all values equaling 1.
#Assign the array to variable "b"
b = np.ones((5,2,3), dtype= int)

In [6]:
#6. Print b.
print(b)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


In [7]:
#7. Do a and b have the same size? How do you prove that in Python code?
print(a.size==b.size)
#same "size" but not "shape" a is 2x3x5 and b is 5x2x3
print(a.shape==b.shape)

True
False


In [8]:
#8. Are you able to add a and b? Why or why not?
#They have different shape

In [9]:
#9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".
c = np.transpose(b, (1,2,0))
print(c.shape)

(2, 3, 5)


In [10]:
#10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?
d = a+c


In [11]:
#11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.
print(a)
print('---------------')
print(d)
#It's a one to one sum of each value of each matrix#12. Multiply a and c. Assign the result to e.



[[[0.16316074 0.75047108 0.14130161 0.70955742 0.85998858]
  [0.93324297 0.18912228 0.1962586  0.0515107  0.70624949]
  [0.02135796 0.10704109 0.54889578 0.73649399 0.98778808]]

 [[0.00635736 0.35127666 0.01824112 0.28142591 0.85660664]
  [0.54823925 0.26497566 0.52960075 0.57961704 0.44223704]
  [0.78766805 0.15292788 0.7055626  0.28157866 0.89320345]]]
---------------
[[[1.16316074 1.75047108 1.14130161 1.70955742 1.85998858]
  [1.93324297 1.18912228 1.1962586  1.0515107  1.70624949]
  [1.02135796 1.10704109 1.54889578 1.73649399 1.98778808]]

 [[1.00635736 1.35127666 1.01824112 1.28142591 1.85660664]
  [1.54823925 1.26497566 1.52960075 1.57961704 1.44223704]
  [1.78766805 1.15292788 1.7055626  1.28157866 1.89320345]]]


In [12]:
#12. Multiply a and c. Assign the result to e.

e = a*c
print(e)
print('------------')
print(a)

[[[0.16316074 0.75047108 0.14130161 0.70955742 0.85998858]
  [0.93324297 0.18912228 0.1962586  0.0515107  0.70624949]
  [0.02135796 0.10704109 0.54889578 0.73649399 0.98778808]]

 [[0.00635736 0.35127666 0.01824112 0.28142591 0.85660664]
  [0.54823925 0.26497566 0.52960075 0.57961704 0.44223704]
  [0.78766805 0.15292788 0.7055626  0.28157866 0.89320345]]]
------------
[[[0.16316074 0.75047108 0.14130161 0.70955742 0.85998858]
  [0.93324297 0.18912228 0.1962586  0.0515107  0.70624949]
  [0.02135796 0.10704109 0.54889578 0.73649399 0.98778808]]

 [[0.00635736 0.35127666 0.01824112 0.28142591 0.85660664]
  [0.54823925 0.26497566 0.52960075 0.57961704 0.44223704]
  [0.78766805 0.15292788 0.7055626  0.28157866 0.89320345]]]


In [13]:
#13. Does e equal to a? Why or why not?
a == e
#it is the same one to one

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

In [14]:
#14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)

In [21]:
#15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.

f = np.empty((2,3,5))
f1= np.empty((2,3,5))

In [22]:

#16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
#If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
#If a value equals to d_mean, assign 50 to the corresponding value in f.
#Assign 0 to the corresponding value(s) in f for d_min in d.
#Assign 100 to the corresponding value(s) in f for d_max in d.
#In the end, f should have only the following values: 0, 25, 50, 75, and 100.
#Note: you don't have to use Numpy in this question.

f = np.copy(d)
f[f==d_min]= 0
f[(f>d_min) & (f<d_mean)]= 25
f[f==d_mean]=50
f[(f>d_mean)& (f<d_max)]= 75
f[f==d_max]=100
print(f)





[[[ 25.  75.  25.  75.  75.]
  [ 75.  25.  25.  25.  75.]
  [ 25.  25.  75.  75. 100.]]

 [[  0.  25.  25.  25.  75.]
  [ 75.  25.  75.  75.  25.]
  [ 75.  25.  75.  25.  75.]]]


In [26]:
for i in range(d.size):
    if d.item(i) >d_mean and d.item(i)<d_max:
        f1.itemset(i,75)
    elif d.item(i) <d_mean and d.item(i)>d_min:
        f1.itemset(i,25)
    elif d.item(i)== d_max:
        f1.itemset(i,100)
    elif d.item(i)== d_mean:
        f1.itemset(i,50)
    elif d.item(i)== d_min:
        f1.itemset(i,0)
f1


array([[[ 25.,  75.,  25.,  75.,  75.],
        [ 75.,  25.,  25.,  25.,  75.],
        [ 25.,  25.,  75.,  75., 100.]],

       [[  0.,  25.,  25.,  25.,  75.],
        [ 75.,  25.,  75.,  75.,  25.],
        [ 75.,  25.,  75.,  25.,  75.]]])

In [18]:
#"""
#17. Print d and f. Do you have your expected f?

print(d)
print(f)


[[[1.16316074 1.75047108 1.14130161 1.70955742 1.85998858]
  [1.93324297 1.18912228 1.1962586  1.0515107  1.70624949]
  [1.02135796 1.10704109 1.54889578 1.73649399 1.98778808]]

 [[1.00635736 1.35127666 1.01824112 1.28142591 1.85660664]
  [1.54823925 1.26497566 1.52960075 1.57961704 1.44223704]
  [1.78766805 1.15292788 1.7055626  1.28157866 1.89320345]]]
[[[ 25.  75.  25.  75.  75.]
  [ 75.  25.  25.  25.  75.]
  [ 25.  25.  75.  75. 100.]]

 [[  0.  25.  25.  25.  75.]
  [ 75.  25.  75.  75.  25.]
  [ 75.  25.  75.  25.  75.]]]


In [30]:
#18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values
#("A", "B", "C", "D", and "E") to label the array elements?

fa = np.chararray((2,3,5))


for i in range(d.size):
    if d.item(i) >d_mean and d.item(i)<d_max:
        fa.itemset(i,"D")
    elif d.item(i) <d_mean and d.item(i)>d_min:
        fa.itemset(i,'B')
    elif d.item(i)== d_max:
        fa.itemset(i,'E')
    elif d.item(i)== d_mean:
        fa.itemset(i,'C')
    elif d.item(i)== d_min:
        fa.itemset(i,'A')
fa


chararray([[[b'B', b'D', b'B', b'D', b'D'],
            [b'D', b'B', b'B', b'B', b'D'],
            [b'B', b'B', b'D', b'D', b'E']],

           [[b'A', b'B', b'B', b'B', b'D'],
            [b'D', b'B', b'D', b'D', b'B'],
            [b'D', b'B', b'D', b'B', b'D']]], dtype='|S1')