In [1]:
import pandas as pd
import numpy as np
import matplotlib as plt

In [10]:
a = list(range(1,6))
b= [a,a]
print(b)

[[1, 2, 3, 4, 5], [1, 2, 3, 4, 5]]


In [17]:
c = np.random.random((5,5))
print(c)

[[0.92789403 0.02110844 0.47822286 0.84081437 0.29594853]
 [0.87016601 0.6007362  0.03404803 0.70842216 0.06217264]
 [0.0033968  0.61757088 0.38461896 0.92088024 0.96508952]
 [0.70613546 0.76483227 0.72611966 0.45183556 0.2989065 ]
 [0.84333968 0.64649949 0.84864566 0.72995585 0.21834641]]


In [21]:
c[:,0]

array([0.92789403, 0.87016601, 0.0033968 , 0.70613546, 0.84333968])

In [25]:
c[:][0]

array([0.92789403, 0.02110844, 0.47822286, 0.84081437, 0.29594853])

In [28]:
lst = [i for i in range(10)]

In [33]:
serie = pd.Series(lst)
serie.values

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
serie.index

RangeIndex(start=0, stop=10, step=1)

In [ ]:
serie= pd.Series(lst,)